# Generated by Django 5.0.6 on 2024-06-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_updated', models.TextField(auto_created=True)),
                ('post_title', models.CharField(max_length=255)),
                ('post_details', models.TextField()),
                ('post_dates', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
