# Generated by Django 5.0.6 on 2024-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
